# cloudformation solution goes here
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template that forms the anomaly detection pipeline for DS5220 Data Project 1

Parameters:
  InstanceType:
    Description: The EC2 instance type
    Type: String
    Default: t3.micro
  KeyName:
    Description: Name of an existing EC2 key pair to allow SSH access
    Type: 'AWS::EC2::KeyPair::KeyName'
  UvaId:
    Description: Your UVA computing ID (to name bucket)
    Type: String
    MinLength: 3
    MaxLength: 9
  SSHLocation:
    Description: "Copy your IP from https://checkip.amazonaws.com and add /32 (e.g., 1.2.3.4/32)"
    Type: String
    Default: "0.0.0.0/0"

Resources:
  # SNS topic creation
  SNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: ds5220-dp1

  SnsTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics: [!Ref SNSTopic]
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SNSTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:::${UvaId}-ds5220-dp1'    
  
  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: SnsTopicPolicy
    Properties:
      # Example: Calculate bucket name from two parameters using !Sub
      BucketName: !Sub ${UvaId}-ds5220-dp1
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectCreated:*'
            Topic: !Ref SNSTopic
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: raw/
                  - Name: suffix
                    Value: .csv
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-bucket
  # Security Group allowing ports 80 and 22
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH and FastAPI access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
          Description: Allow FastAPI access
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
          Description: Allow SSH access
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ec2-sg

  # IAM Role for EC2 instance
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: S3FullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource: 
                  - !Sub 'arn:aws:s3:::${UvaId}-ds5220-dp1'
                  - !Sub 'arn:aws:s3:::${UvaId}-ds5220-dp1/*'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ec2-role

  # IAM Instance Profile to attach the role to EC2
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b6c6ebed2801a5cb
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Bootstrapping script
          export BUCKET_NAME=${UvaId}-ds5220-dp1
          echo "export BUCKET_NAME=${UvaId}-ds5220-dp1" >> /etc/environment
          
          # Update and install Python + pip
          apt-get update -y
          apt-get install -y git python3 python3-pip python3-venv
          
          # set up app
          cd /home/ubuntu
          git clone https://github.com/randa-ama/anomaly-detection.git
          cd anomaly-detection

          # set up virtual environment
          python3 -m venv venv
          source venv/bin/activate
          ./venv/bin/pip install -r requirements.txt
          
          # Start FastAPI
          ./venv/bin/python3 -m uvicorn app:app --host 0.0.0.0 --port 8000 &

      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ec2-instance

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  ElasticIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2Instance
      AllocationId: !GetAtt ElasticIP.AllocationId

Outputs:
  AppURL:
    Description: URL to subscribe to SNS
    Value: !Sub 'http://${ElasticIP}:8000/notify'
  BucketName:
    Value: !Ref S3Bucket
  
